### ISSUE TITLE
Fix wrong version number in FOG data

### ISSUE THREAD

**Issue by Iinh** [mozilla/glam#1941]
While testing FOG probes on dev I noticed something's wrong with the Glean data: the version number for all FOG metrics is `1024` (instead of the standard Firefox versions 98, 99, 100, etc.) 

- [glean_baseline_duration](http://-%20https//dev.glam.nonprod.dataops.mozgcp.net/fog/probe/glean_baseline_duration/explore?aggType=avg&aggregationLevel=version&currentPage=1&ping_type=*)
- [fog_initialization](https://dev.glam.nonprod.dataops.mozgcp.net/fog/probe/fog_initialization/explore?aggType=avg&aggregationLevel=version&currentPage=1&ping_type=*)

Database check to confirm that all metrics have 1024 as the version number:
```
postgres=# SELECT version from glam_fog_aggregation GROUP BY version;
 version 
---------
    1024
(1 row)
```
![CleanShot 2022-04-18 at 11 23 39@2x](https://user-images.githubusercontent.com/28797553/164281511-85228f0f-cb53-45d1-ae98-2e519f5e42e7.png)

**Comment by akkomar** [comment]
It looks like we're getting FOG pings from clients that report their version number as ` 1024.0.0 `.

ETL jobs filter for pings from the [last 3 versions we've seen](https://github.com/mozilla/bigquery-etl/blob/main/sql/glam-fenix-dev/glam_etl/firefox_desktop_glam_nightly__clients_scalar_aggregates_v1/query.sql#L146), so [on the days when in the last month we've seen more than 5 clients](https://github.com/mozilla/bigquery-etl/blob/main/bigquery_etl/glam/templates/latest_versions_v1.sql#L25) reporting version 1024 we'll pull in only this version into aggregations.

Ideally the easiest way to filter out rogue builds would be to use buildhub data, [like we do with the legacy desktop telemetry](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_scalar_aggregates_v1.sql.py#L55-L60). Although it looks like this alone will not be enough here as [version 1024 is reported together with valid build ids that are sent also with valid version numbers](https://sql.telemetry.mozilla.org/queries/85679/source).

However we should be able to filter out these pings based on both `build.build.id` and `build.target.version` joined from the buildhub table.

We could also consider bumping [client count threshold in FOG latest_versions table from 5](https://github.com/mozilla/bigquery-etl/blob/main/bigquery_etl/glam/templates/latest_versions_v1.sql#L25) to 2000 in order to make it consistent with the [legacy telemetry ETL](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/telemetry_derived/latest_versions/query.sql#L11). It's not clear to me why is this threshold set to 5, but I see similar client counts in `main_v4` vs `firefox_desktop_stable.baseline_v1` so it looks to be the right thing to do.

Interesting thing about these pings is that they all come from Windows (https://sql.telemetry.mozilla.org/queries/85680/source) - could this be a sign of some bug? /cc @chutten

**Comment by chutten** [comment]
Looks like you may need to re-save that last query. It has no results. : )

FOG gets its app version from the same place Telemetry does, so it should suffer from identical failings... modulo the difference in timing. "baseline" pings are sent earlier and more frequently than "main" pings so may access the data at a different time and repeat it more frequently.

**Comment by chutten** [comment]
Hrm. Maybe a 1% sample is too small to find v1024, but from this look "main" pings don't show v1024: https://sql.telemetry.mozilla.org/queries/85688/source

(( they do show 99.0, 100.0, 91.0, and 98.0.2 though ))

**Comment by akkomar** [comment]
> Looks like you may need to re-save that last query. It has no results. : )

Done.

> Hrm. Maybe a 1% sample is too small to find v1024, but from this look "main" pings don't show v1024: https://sql.telemetry.mozilla.org/queries/85688/source

I switched this query to the full main ping table - still no v1024.

**Comment by chutten** [comment]
Well, poo. Looks like there's definitely something to investigate. I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1768187 for the investigation, but don't let this stop you from filtering this subset out in the meantime.

Thank you for bringing this to my attention!

**Comment by akkomar** [comment]
> However we should be able to filter out these pings based on both `build.build.id` and `build.target.version` joined from the buildhub table.
> 
After some investigations I don't think this is the right thing to do. It seems like `client_info.app_display_version` reported by FOG cannot be reliably matched to `build.target.version` published in Buildhub.
These values do not exactly match for release candidate builds - versions reported in FOG telemetry have their suffixes stripped. For example, beta build with `build.target.version = 100.0b1` gets reported as `client_info.app_display_version = 100.0`. For contrast, legacy telemetry has `application.version` and `application.display_version` - the former seems to be behaving similar to FOG's `client_info.app_display_version`, the latter has the full, unstripped version strings.

This issue is particularly visible on a beta channel - ~70% of clients' pings would be filtered out there. Although this could be worked around by regexes and string manipulation in queries, I wouldn't be sure about robustness of such solution.

It would be worth to fully understand version naming conventions at some point, but at the moment I think we should consider:
* filtering FOG pings using `build.target.version`, in the same way as we do in the legacy telemetry GLAM-ETL, and
* explicitly filtering out version `1024.0.0` with a comment about the bug filed above.

**Comment by akkomar** [comment]
> It would be worth to fully understand version naming conventions at some point, but at the moment I think we should consider:
> 
>     * filtering FOG pings using `build.target.version`, in the same way as we do in the legacy telemetry GLAM-ETL, and
> 
>     * explicitly filtering out version `1024.0.0` with a comment about the bug filed above.

This was implemented in https://github.com/mozilla/bigquery-etl/pull/2957, merged and successfully ran today. I will now work on backfilling ETL tables. Next step would be to do an import to the dev environment for verification.

**Comment by Iinh** [comment]
> This was implemented in https://github.com/mozilla/bigquery-etl/pull/2957, merged and successfully ran today. I will now work on backfilling ETL tables. Next step would be to do an import to the dev environment for verification.

Thanks @akkomar for working on this. I imported a fresh batch of GLEAN data today (`./manage.py import_glean_aggs`) to test, however I'm still seeing `1024` listed as version for some FOG metrics such as [glean_baseline_duration](http://-%20https//dev.glam.nonprod.dataops.mozgcp.net/fog/probe/glean_baseline_duration/explore?aggType=avg&aggregationLevel=version&currentPage=1&ping_type=*), [fog_initialization](https://dev.glam.nonprod.dataops.mozgcp.net/fog/probe/fog_initialization/explore?aggType=avg&aggregationLevel=version&currentPage=1&ping_type=*). Not sure if I missed something?

**Comment by akkomar** [comment]
@Iinh I am running the backfill right now, I'll let you know when that's ready.

**Comment by akkomar** [comment]
Backfill has finished.
